### ISSUE TITLE
on AWS the supervisord.conf file is wrong.

### ISSUE THREAD

**Issue by drj11** [parklab/refinery-platform#923]
As @ilya points out in Trello, the `supervisord.conf` file also needs templating.

**Comment by drj11** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;uGTokZN9&#x2F;225-troubleshoot-supervisord-not-starting-automatically-during-provisioning-on-aws"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> troubleshoot supervisord not starting automatically during provisioning on AWS</a>

**Comment by drj11** [comment]
Fixed by https://github.com/parklab/refinery-platform/pull/937

**Comment by hackdna** [comment]
Still a problem when running commit 11b9d809. In `supervisord.conf` only `[program:worker1]` section contains
`environment = PATH="/home/ubuntu/.virtualenvs/refinery-platform/bin"`. All others contain `environment = PATH="/bin"`.

**Comment by drj11** [comment]
Yes, the previous PR, #937, still wasn't right.

Now that you've merged that one, I've made another PR which should be right this time. #940

**Comment by hackdna** [comment]
It's #941, not #940. I'll merge it and test it.

**Comment by drj11** [comment]
@ilya did you know that you don't need to merge a branch to test deployment on AWS by the way? (as long as it's a pushed commit; it uses your current commit (from `git rev-parse HEAD`) as the deploy target).

**Comment by hackdna** [comment]
Yes, the problem is that you can't easily switch branches if you have uncommitted local changes. What would great is to be able to specify an arbitrary commit as the deploy target.

**Comment by drj11** [comment]
you can `git stash`, change branch, deploy, change branch back, `git stash pop`. but that is long enough to be error prone. In principle what you suggest is doable because all the current thing does is set `GIT_BRANCH` (see the `stack.py` script). That could be changed so it was possible to override.
